#!/usr/bin/env bash
# Wipe regenerable build artifacts for macDros.
#
#   ./scripts/clean.sh           SPM .build/ + project DerivedData (default)
#   ./scripts/clean.sh --light   SPM .build/ only (fastest; leaves Xcode cache)
#   ./scripts/clean.sh --all     adds .xcodeproj + fetched binaries (next bootstrap
#                                will redownload adb + scrcpy-server.jar)
#
# Safe to run anytime — everything removed here is regenerated by `swift build`,
# Xcode, `xcodegen generate`, or `scripts/bootstrap.sh`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

MODE="${1:-default}"

case "${MODE}" in
  --light|--default|"") ;;
  --all|default) ;;
  -h|--help)
    sed -n '2,12p' "${BASH_SOURCE[0]}"
    exit 0
    ;;
  *)
    echo "unknown mode: ${MODE}"
    exit 2
    ;;
esac

bytes_human() {
  if command -v gnumfmt >/dev/null 2>&1; then
    gnumfmt --to=iec --suffix=B "$1"
  else
    awk -v b="$1" 'BEGIN{
      split("B KB MB GB TB", units)
      for (i=1; b>=1024 && i<5; i++) b/=1024
      printf "%.1f %s\n", b, units[i]
    }'
  fi
}

before=$(du -ks "${ROOT}" 2>/dev/null | awk '{print $1*1024}')

echo "==> SPM .build/ caches"
find "${ROOT}/Packages" -type d -name .build -prune -exec rm -rf {} +
echo "    cleared"

if [[ "${MODE}" != "--light" ]]; then
  echo "==> Xcode DerivedData (this project only)"
  rm -rf "${HOME}/Library/Developer/Xcode/DerivedData/DroidMirroring-"*
  echo "    cleared"
fi

if [[ "${MODE}" == "--all" ]]; then
  echo "==> generated .xcodeproj"
  rm -rf "${ROOT}/DroidMirroring.xcodeproj"
  echo "    cleared — rerun: xcodegen generate"

  echo "==> fetched binaries (adb, scrcpy-server, Licenses)"
  rm -f  "${ROOT}/App/Resources/adb" "${ROOT}/App/Resources/.adb.sha"
  rm -f  "${ROOT}/App/Resources/scrcpy-server.jar" "${ROOT}/App/Resources/scrcpy-server-"*.jar
  rm -f  "${ROOT}/App/Resources/Licenses/LICENSE-scrcpy" "${ROOT}/App/Resources/Licenses/LICENSE-adb"
  echo "    cleared — rerun: scripts/bootstrap.sh"
fi

after=$(du -ks "${ROOT}" 2>/dev/null | awk '{print $1*1024}')
freed=$(( before - after ))

echo ""
echo "freed approximately $(bytes_human "${freed}")"
echo "project size now    $(bytes_human "${after}")"
